### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by BobEboph**
I followed your suggestion from last time and examined the sources when I found typos. I was also able to find an alternate PG translation to compare against when I disagreed with both the OLS scans and the PG ebook. Relevant source pages are linked when necessary.

When you get a pull request, do you have to accept all my commits, or can you pick and choose? Would it help you if I made a PR for typo fixes and another for more debatable changes?

### CODE REVIEW

**Comment by acabal** [comment]
Hi Bob, thanks for the hard work!

A few notes:

1. For dd054301 you removed the hyphen that I inserted after your previous pull request tried to change "too" to "two". I added the hyphen for clarity since others might also think that "too" was a mistake.
2. For all commits where you modernize spelling, please preface the commit message with `[Editorial]`. This is so people can go back and undo those changes if they want. Please also do that for d92f7c1bd and 917b26 and d6bd84

You can rebase this series of commits to change the messages and alter dd054301. I'm not sure if you can do a force push to Github for this pull request, or if you have to open a new one.

Otherwise great work. Thanks!

**Comment by acabal** [comment]
Hi Bob, just wanted to check in to see if you had this on your radar. Let me know!

**Comment by BobEboph** [comment]
Happy to be able to contribute. I love the idea of this project and the improvement over the PG and most other free ebooks. Unfortunately I got busy with work and vacation planning right after I issued that PR, so I haven't been able to make the changes you've requested, and probably won't for at least a week.

1. This is my first PR for this book, but it's not surprising someone had an issue with that part. I just checked that alternate translation and it clarifies that there are two young colts:  [The onagers, who had two pretty colts, were most often mounted by Gideon Spilett and Herbert](https://www.gutenberg.org/files/1268/1268-h/1268-h.htm#link2HCH0040). Either awkward wording in the White translation, or a typo between his translation and the typesetter. Either way, I'll update this commit to "two young onagers" if that's OK with you.

2. Is it a part of the mission of Standard Ebooks to modernize spelling? I don't mind modernizing or not, I just want to be consistent with everything else.

**Comment by acabal** [comment]
OK, sounds good for point 1.

Yes, part of the project is to do some light spelling modernization. 99% of this is accomplished with the `modernize-spelling` script. Certain individual modernizations can be made by individual producers on a case by case basis. Usually we look at Google n-grams to see whether a particular spelling has been superseded by a modern one for 50+ years.

**Comment by acabal** [comment]
Oh, and take your time, just wanted to make sure this was on your radar. The actual Git activity should be quite simple once you figure out the right incantation. If you can't update this pull request just open a fresh one, no problem.

**Comment by acabal** [comment]
Bob, have you had a moment to wrap this up? I'd hate for us to not be able to pull in these updates.

**Comment by acabal** [comment]
Rebased and merged in b8ed0fc56b19da0abd5d3a835f092d383cb4aa6a

**Pull request closed without merging**
